url<-"https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
download.file(url,destfile="UCI HAR Dataset.zip")
unzip("UCI HAR Dataset.zip",exdir="UCI HAR Dataset")
library(dplyr)
path<-paste(getwd(),"UCI HAR Dataset/UCI HAR Dataset",sep="/")
setwd(path)
features<-read.table("features.txt")
activity_labels<-read.table("activity_labels.txt")
activity_labels<-tolower(activity_labels$V2)
activity_labels<-sub("_"," ",activity_labels)
setwd(paste(path,"test",sep="/"))
x_test<-read.table("X_test.txt")
y_test<-read.table("Y_test.txt")
subject_test<-read.table("subject_test.txt")
setwd(paste(path,"train",sep="/"))
x_train<-read.table("X_train.txt")
y_train<-read.table("Y_train.txt")
subject_train<-read.table("subject_train.txt")
test<-cbind(subject_test,y_test,x_test)
train<-cbind(subject_train,y_train,x_train)
dat<-tbl_df(rbind(test,train))
cols<-c("subject","activity",as.character(features$V2))
cols<-make.names(names=cols,unique=TRUE,allow_=TRUE)
colnames(dat)<-cols
dat<-select(dat,subject,activity,contains("mean"),contains("std"))
library(stringr)
cols1<-names(dat)
cols1<-tolower(str_replace_all(cols1,"[[:punct:]]",""))
cols1<-sub("acc","acceleration",cols1)
cols1<-sub("gyro","gyroscope",cols1)
cols1<-sub("mag","magnitude",cols1)
cols1<-sub("freq","frequency",cols1)
cols1<-sub("std","standarddeviation",cols1)
cols1<-sub("^f","frequency",cols1)
cols1<-sub("^t","time",cols1)
cols1<-sub("x$","directionx",cols1)
cols1[3:88]<-sub("y$","directiony",cols1[3:88])
cols1<-sub("z$","directionz",cols1)
colnames(dat)<-cols1
dat$activity<-activity_labels[dat$activity]
dat<-group_by(dat,subject,activity)
dat2<-summarize_each(dat,funs(mean))
